### ISSUE TITLE
Incredible lag spike when QuestTask.isComplete

### ISSUE THREAD

**Issue by Sufike** [FTBTeam/FTB-Quests#237]
Hi,

We got a little issue on a modpack using your mod, we got hugeeee lag spike (19.998TPS to 3TPS) when someone come on the server.

```
Last tick 0.22995856s ago."Server thread" RUNNABLE
        at com.feed_the_beast.ftbquests.quest.task.QuestTask.isComplete(QuestTask.java:87)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:433)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.isComplete(Quest.java:441)
        at com.feed_the_beast.ftbquests.quest.Quest.canStartTasks(Quest.java:504)
        at com.feed_the_beast.ftbquests.util.FTBQuestsInventoryListener.detect0(FTBQuestsInventoryListener.java:61)
        at com.feed_the_beast.ftbquests.util.FTBQuestsInventoryListener.detect(FTBQuestsInventoryListener.java:36)
        at com.feed_the_beast.ftbquests.util.FTBQuestsInventoryListener.func_71111_a(FTBQuestsInventoryListener.java:104)
        at net.minecraft.inventory.Container.func_75142_b(Container.java:91)
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
        at net.minecraft.world.World.func_72866_a(World.java:1993)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
        at net.minecraft.world.World.func_72870_g(World.java:1955)
        at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
        at net.minecraft.world.World.func_72939_s(World.java:1734)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)

```

Have you got any idea of how to fix that ?

**Comment by Clem-Fern** [comment]
A crash report of this problem : 
https://pastebin.com/iDa5gFHf

Mod version : FTBQuests-1.5.2.148.jar

**Comment by LatvianModder** [comment]
https://github.com/FTBTeam/FTB-Quests/issues/226
