### ISSUE TITLE
FTBQuest or a FTBLib last bug have I found in the startup of Forge

### ISSUE THREAD

**Issue by Titoo8899** [FTBTeam/FTB-Quests#309]
Hi,
this is the last bug that I have found. The game start in the first time normal but the last stept of 7 of 7 crash it the game. Please check this and fix the problem. The other problems was clear.

FTB Quests 1.6.1.160
FTB  Lib 5.4.3.115
Itemfilter 1.0.3.12

Crash Report:
Error: java.lang.NoClassDefFoundError: javafx/scene/image/Pixelformat

-------

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 6/18/19 10:33 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: javafx/scene/image/PixelFormat
	at com.feed_the_beast.ftblib.client.FTBLibClientEventHandler.onRenderTick(FTBLibClientEventHandler.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_62_FTBLibClientEventHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1116)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: javafx.scene.image.PixelFormat
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 167765520 bytes (159 MB) / 939524096 bytes (896 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version               | Source                                                                | Signature                                |
	|:------ |:-------------------------- |:--------------------- |:--------------------------------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft                  | 1.12.2                | minecraft.jar                                                         | None                                     |
	| UCHIJA | mcp                        | 9.42                  | minecraft.jar                                                         | None                                     |
	| UCHIJA | FML                        | 8.0.99.99             | forge-1.12.2-14.23.5.2768.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                      | 14.23.5.2768          | forge-1.12.2-14.23.5.2768.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | better_diving              | 1.3.63                | BetterDiving-1.12.2-1.3.63.jar                                        | None                                     |
	| UCHIJA | mts                        | 14.3.1                | Immersive+Vehicles-1.12.2-14.3.1.jar                                  | None                                     |
	| UCHIJA | unuparts                   | 1.11.2                | UNU+Parts+Pack+[MTS]+1.10.2-14.0.0-1.11.2.jar                         | None                                     |
	| UCHIJA | blackthorne                | 1.11.2                | BlackThorne+Empire+Vehicles+[MTS]+[IR]+1.10.2-14.0.0-1.5.0-1.11.2.jar | None                                     |
	| UCHIJA | crossbow                   | 1.0.0                 | Crossbow-Mod-1.12.2-1.0.0-fix.jar                                     | None                                     |
	| UCHIJA | ftblib                     | 5.4.3.115             | FTBLib-5.4.3.115.jar                                                  | None                                     |
	| UCHIJA | itemfilters                | 1.0.3.12              | ItemFilters-1.0.3.12.jar                                              | None                                     |
	| UCHIJA | ftbquests                  | 1.6.1.160             | FTBQuests-1.6.1.160.jar                                               | None                                     |
	| UCHIJA | holdyerbreath              | 1.12.2-1.1.2          | holdyerbreath-1.12.2-1.1.2.jar                                        | None                                     |
	| UCHIJA | mtsseagullcivilpack        | 2.0.0                 | Immersive+Vehicles+(IV)+Seagull's+civil+pack+1.22.0.jar               | None                                     |
	| UCHIJA | mtsseagullmilitarypack     | 1.4.0                 | Immersive+Vehicles+(IV)+Seagull's+military+pack+1.7.3.jar             | None                                     |
	| UCHIJA | mtsseagulltrinpartpack     | 1.0.0                 | Immersive+Vehicles+(IV)+Seagull's+trin+parts+pack+1.11.2.jar          | None                                     |
	| UCHIJA | melvinssignpack            | 1.0.0                 | Melvins_Simple_Sign_Pack-Beta-0.0.5.jar                               | None                                     |
	| UCHIJA | mtsofficialpack            | 11.0.0                | MTS_Official_Pack_V11.jar                                             | None                                     |
	| UCHIJA | merlynofficialpack         | 5.4.0                 | Merlyn's+Luxurious+Vehicles+Pack+5.4.jar                              | None                                     |
	| UCHIJA | mmmpack                    | 1.0.3                 | Moonspire+Metropolitan+Motors+[MTS]+1.10.2-14.0.0-1.0.3.jar           | None                                     |
	| UCHIJA | blueboyscaterpillarmtspack | 1.1.0                 | MTS_Caterpillar_Pack_V1.1.1.jar                                       | None                                     |
	| UCHIJA | mtsheavyindustrialbyadamrk | 6.0.0                 | MTS_Heavy_Industrial_by_AdamRK_1.9.0.jar                              | None                                     |
	| UCHIJA | jblavehaero                | 1.0.0                 | MTS_P1_airportpack.jar                                                | None                                     |
	| UCHIJA | t3gssksignspack            | 1.0.1                 | Tim3Game's+European+Signs+Pack+1.0.1.jar                              | None                                     |
	| UCHIJA | nofog                      | 1.12.2-1.12.2-1.0.3.0 | NoFog-1.12.2b3.jar                                                    | 0bf221d944c89aaf3ccb7b8315148f222be50739 |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3308' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3308, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz

**Comment by Titoo8899** [comment]
All crash fix. Thanks
