### ISSUE TITLE
Custom NPCs support fixes and suggestions

### ISSUE THREAD

**Issue by fl1pp3r** [FTBTeam/FTB-Quests#343]
the "CustomNPCs Faction" reward option writes data to "points", but tries to read data from "required_points", causing it to reset to 0 every time

suggestions:
add a "CustomNPCs Quest Complete" task using PlayerQuestController.isQuestFinished()

rename "CustomNPCs Quest" task to "CustomNPCs Active Quest" (because it checks if the quest is active and not complete)
add "CustomNPCs Complete Quest" reward using PlayerQuestController.setQuestFinished()

attempting to add a "CustomNPCs Mail" reward crashes the game:
```
java.lang.NoSuchFieldError: questTitle
    at com.feed_the_beast.ftbquests.integration.customnpcs.NPCMailReward.lambda$getConfig$6(NPCMailReward.java:111)
    at com.feed_the_beast.ftbquests.integration.customnpcs.NPCMailReward$$Lambda$2985/789172608.get(Unknown Source)
    at com.feed_the_beast.ftblib.lib.config.ConfigString$SimpleString.getString(ConfigString.java:41)
    at com.feed_the_beast.ftblib.lib.config.ConfigString.copy(ConfigString.java:120)
    at com.feed_the_beast.ftblib.lib.config.ConfigString$SimpleString.copy(ConfigString.java:26)
    at com.feed_the_beast.ftblib.lib.config.ConfigValueInstance.setDefaultValue(ConfigValueInstance.java:84)
    at com.feed_the_beast.ftblib.lib.config.ConfigGroup.add(ConfigGroup.java:157)
    at com.feed_the_beast.ftblib.lib.config.ConfigGroup.addString(ConfigGroup.java:185)
    at com.feed_the_beast.ftblib.lib.config.ConfigGroup.addString(ConfigGroup.java:190)
    at com.feed_the_beast.ftbquests.integration.customnpcs.NPCMailReward.getConfig(NPCMailReward.java:111)
    at com.feed_the_beast.ftbquests.quest.reward.RewardType$1.openCreationGui(RewardType.java:117)
    at com.feed_the_beast.ftbquests.gui.tree.ButtonAddReward.lambda$onClicked$1(ButtonAddReward.java:43)
    at com.feed_the_beast.ftbquests.gui.tree.ButtonAddReward$$Lambda$2952/1841173022.run(Unknown Source)
    at com.feed_the_beast.ftblib.lib.gui.ContextMenuItem.onClicked(ContextMenuItem.java:92)
    at com.feed_the_beast.ftblib.lib.gui.ContextMenu$CButton.onClicked(ContextMenu.java:66)
    at com.feed_the_beast.ftblib.lib.gui.Button.mousePressed(Button.java:69)
    at com.feed_the_beast.ftblib.lib.gui.Panel.mousePressed(Panel.java:353)
    at com.feed_the_beast.ftblib.lib.gui.ContextMenu.mousePressed(ContextMenu.java:126)
    at com.feed_the_beast.ftblib.lib.gui.Panel.mousePressed(Panel.java:353)
    at com.feed_the_beast.ftblib.lib.gui.GuiBase.mousePressed(GuiBase.java:362)
    at com.feed_the_beast.ftblib.lib.gui.GuiWrapper.mouseClicked(GuiWrapper.java:53)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at com.feed_the_beast.ftblib.lib.gui.GuiWrapper.handleMouseInput(GuiWrapper.java:99)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by LatvianModder** [comment]
"points" "required_points" wow, fail lol.. I didn't do much testing with this mod, I will fix those issues
