### ISSUE TITLE
[Crash] Exception in server tick loop

### ISSUE THREAD

**Issue by JoshuaKRomero** [FTBTeam/FTB-Quests#374]
[crash-2020-01-29_11.18.43-server.txt](https://github.com/FTBTeam/FTB-Quests/files/4129487/crash-2020-01-29_11.18.43-server.txt)
Description: Exception in server tick loop

java.lang.StackOverflowError: Exception in server tick loop
	at io.netty.util.internal.logging.JdkLogger.log(JdkLogger.java:602)
	at io.netty.util.internal.logging.JdkLogger.warn(JdkLogger.java:482)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:509)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
	at com.feed_the_beast.ftblib.lib.net.MessageToClient.sendToAll(MessageToClient.java:43)
	at com.feed_the_beast.ftbquests.quest.task.TaskData.setProgress(TaskData.java:59)
	at com.feed_the_beast.ftbquests.quest.task.ItemTask$Data.submitTask(ItemTask.java:463)
	at com.feed_the_beast.ftbquests.util.FTBQuestsInventoryListener.detect(FTBQuestsInventoryListener.java:53)
	at com.feed_the_beast.ftbquests.quest.task.TaskData.setProgress(TaskData.java:86)
	at com.feed_the_beast.ftbquests.quest.task.ItemTask$Data.submitTask(ItemTask.java:463)

This happens when I load up a single player world the first time only and similarly happens every time when starting up my server.

**Comment by JoshuaKRomero** [comment]
Update: It has been resolved by removing any Roots related quests.
