### ISSUE TITLE
Crash Exception in server tick loop

### ISSUE THREAD

**Issue by JoshuaKRomero** [FTBTeam/FTB-Quests#376]
https://pastebin.com/0Aj9RBZw

`Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.getTitle(QuestObjectBase.java:378)
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.getUnformattedTitle(QuestObjectBase.java:401)
	at com.feed_the_beast.ftbquests.quest.reward.RandomReward.readData(RandomReward.java:84)
	at com.feed_the_beast.ftbquests.quest.QuestFile.readDataFull(QuestFile.java:698)
	at com.feed_the_beast.ftbquests.quest.ServerQuestFile.load(ServerQuestFile.java:66)
	at com.feed_the_beast.ftbquests.util.FTBQuestsWorldData.onUniversePreLoaded(FTBQuestsWorldData.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_729_FTBQuestsWorldData_onUniversePreLoaded_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.feed_the_beast.ftblib.lib.EventBase.post(EventBase.java:20)
	at com.feed_the_beast.ftblib.lib.data.Universe.load(Universe.java:370)
	at com.feed_the_beast.ftblib.lib.data.Universe.onWorldLoaded(Universe.java:122)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_592_Universe_onWorldLoaded_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:309)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more`

When I startup my server it refused to load and puts out the same error each time. I have tried removing each quest line individually and nothing has helped except removing them ALL. It loads perfectly fine in singleplayer and I am unsure of how to reproduce this or troubleshoot it.

**Comment by devmane144** [comment]
I'm having the exact same issue

**Comment by JoshuaKRomero** [comment]
> I'm having the exact same issue

Okay, I actually fixed this issue and it was a really simple fix. For me I had an empty folder with no quests in the main quest folder and all I did was delete it and everything worked fine.

**Comment by devmane144** [comment]
> > I'm having the exact same issue
> 
> Okay, I actually fixed this issue and it was a really simple fix. For me I had an empty folder with no quests in the main quest folder and all I did was delete it and everything worked fine.

Thank you for the reply! After trying this solution and failing, I got it to work by re-uploading _all_ the config files and the mod files from the **client** folder to the **server** folder, and although quests wasn't the only problem, your reply got me on the right scent!

**Comment by devmane144** [comment]
For future folks looking into this, I also ran into an error complaining that minecraft couldn't find the ID in the "registry", and that error according to Google is a symptom of config folder mismatch between client and server.

**Comment by MaxNeedsSnacks** [comment]
Thanks for the heads-up for future encounters with this issue!
Either way, this should no longer be an issue in 1.16+ versions of Quests
