### ISSUE TITLE
[1.16.3] Error when autocrafting with AE2

### ISSUE THREAD

**Issue by rehwinkel** [FTBTeam/FTB-Quests#482]
When using the autocrafting feature from applied energistics 2, FTB Quests causes an issue that makes it impossible to use autocrafting. I assume the Event Hanlder from FTB-Quests is called when a recipe is crafted, which in the case of AE2 causes a crash because FTB-Quests expects a player but AE2 doesnt supply a player with the event, causing an NPE.

Stacktrace:
```
[16:25:04] [Server thread/INFO] [AE2:S/]: Exception:
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?] {}
        at com.feed_the_beast.ftbquests.quest.PlayerData.getTaskData(PlayerData.java:77) ~[?:1603.1.0.5] {re:classloading}
        at com.feed_the_beast.ftbquests.util.FTBQuestsInventoryListener.detect(FTBQuestsInventoryListener.java:45) ~[?:1603.1.0.5] {re:classloading}
        at com.feed_the_beast.ftbquests.FTBQuestsEventHandler.itemCrafted(FTBQuestsEventHandler.java:282) ~[?:1603.1.0.5] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerCraftingEvent(BasicEventHooks.java:64) ~[?:?] {re:classloading}
        at appeng.crafting.CraftingTreeProcess.<init>(CraftingTreeProcess.java:75) ~[?:8.1.0-beta.2] {re:classloading}
        at appeng.crafting.CraftingTreeNode.<init>(CraftingTreeNode.java:82) ~[?:8.1.0-beta.2] {re:classloading}
        at appeng.crafting.CraftingJob.getCraftingTree(CraftingJob.java:96) ~[?:8.1.0-beta.2] {re:classloading}
        at appeng.crafting.CraftingJob.<init>(CraftingJob.java:91) ~[?:8.1.0-beta.2] {re:classloading}
        at appeng.me.cache.CraftingGridCache.beginCraftingJob(CraftingGridCache.java:442) ~[?:8.1.0-beta.2] {re:classloading}
        at appeng.core.sync.packets.CraftRequestPacket.serverPacketData(CraftRequestPacket.java:86) ~[?:8.1.0-beta.2] {re:classloading}
        at appeng.core.sync.network.ServerPacketHandler.onPacketData(ServerPacketHandler.java:37) ~[?:8.1.0-beta.2] {re:classloading}
        at appeng.core.sync.network.NetworkHandler.lambda$serverPacket$6(NetworkHandler.java:82) ~[?:8.1.0-beta.2] {re:classloading}
        at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?] {re:classloading}
        at appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:81) ~[?:8.1.0-beta.2] {re:classloading}
```

**Comment by rehwinkel** [comment]
Nevermind, this issue has been fixed in the newest version of the mod. Updating to the newest verison resolved the issue.
