### ISSUE TITLE
1.16.5 Crash on server startup [Build 29]

### ISSUE THREAD

**Issue by Excaliburns** [FTBTeam/FTB-Quests#544]
After updating from build 28 to 29, I get this stacktrace on the server when attempting startup.

```
Failure message: FTB Quests (ftbquests) has failed to load correctly
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: com.feed_the_beast.ftbquests.quest.task.ItemTask.<init>(Quest)void/newInvokeSpecial
Mod Version: version
Mod Issue URL: https://github.com/FTBTeam/FTB-Quests/issues
Exception message: java.lang.ClassNotFoundException: net.minecraft.client.gui.toasts.IToast
Stacktrace:
at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_275] {}
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275] {}
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275] {}
at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_275] {}
at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_275] {}
at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_275] {}
at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_275] {}
at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_275] {}
at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_275] {}
at com.feed_the_beast.ftbquests.quest.task.TaskTypes.<clinit>(TaskTypes.java:24) ~[ftbquests:1605.2.0-build.29] {re:classloading}
at com.feed_the_beast.ftbquests.FTBQuests.<init>(FTBQuests.java:34) ~[ftbquests:1605.2.0-build.29] {re:classloading}
at com.feed_the_beast.ftbquests.FTBQuestsForge.<init>(FTBQuestsForge.java:40) ~[ftbquests:1605.2.0-build.29] {re:classloading}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_275] {}
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_275] {}
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_275] {}
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_275] {}
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_275] {}
at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.0] {re:classloading}
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_275] {}
at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_275] {}
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_275] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_275] {}
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_275] {}
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_275] {}
```

Best guess is something is calling client code from the server?

Versions:
**ftb-gui:** 1605.2.1.39
**architectury:** 1.7.117

**Comment by MaxNeedsSnacks** [comment]
Do you have a full paste of the log?

**Comment by Excaliburns** [comment]
```
[21Feb2021 22:28:38.939] [modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: ftbquests, class com.feed_the_beast.ftbquests.FTBQuestsForge
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: com.feed_the_beast.ftbquests.quest.task.ItemTask.<init>(Quest)void/newInvokeSpecial
	at com.feed_the_beast.ftbquests.quest.task.TaskTypes.<clinit>(TaskTypes.java:24) ~[ftbquests:1605.2.0-build.29]
	at com.feed_the_beast.ftbquests.FTBQuests.<init>(FTBQuests.java:34) ~[ftbquests:1605.2.0-build.29]
	at com.feed_the_beast.ftbquests.FTBQuestsForge.<init>(FTBQuestsForge.java:40) ~[ftbquests:1605.2.0-build.29]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_275]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_275]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_275]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.0]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_275]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_275]
Caused by: java.lang.IllegalAccessError: no such constructor: com.feed_the_beast.ftbquests.quest.task.ItemTask.<init>(Quest)void/newInvokeSpecial
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483) ~[?:1.8.0_275]
	... 16 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/toasts/IToast
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_275]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_275]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_275]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_275]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_275]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_275]
	... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.toasts.IToast
	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_275]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_275]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_275]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_275]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_275]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_275]
	... 16 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_275]
		at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_275]
		at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_275]
		at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_275]
		at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_275]
		at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_275]
		at com.feed_the_beast.ftbquests.quest.task.TaskTypes.<clinit>(TaskTypes.java:24) ~[ftbquests:1605.2.0-build.29]
		at com.feed_the_beast.ftbquests.FTBQuests.<init>(FTBQuests.java:34) ~[ftbquests:1605.2.0-build.29]
		at com.feed_the_beast.ftbquests.FTBQuestsForge.<init>(FTBQuestsForge.java:40) ~[ftbquests:1605.2.0-build.29]
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_275]
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_275]
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_275]
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_275]
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_275]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.0]
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_275]
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_275]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_275]
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_275]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_275]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_275]
```

**Comment by MaxNeedsSnacks** [comment]
I meant a **full** latest.log file, on a site like https://hastebin.com, this is still not giving me enough information unfortunately

**Comment by Excaliburns** [comment]
That's my bad. Should have known. Sorry about that!

https://gist.github.com/Excaliburns/f387b97b4fe3224cd091694ab6db8a2a

**Comment by MaxNeedsSnacks** [comment]
I'm honestly a bit lost with this issue, it's obvious that like you said it's trying to load IToast on the server side but the source for that hasn't changed one bit since the last build, so I'm confused why this is suddenly popping up now

**Comment by MaxNeedsSnacks** [comment]
This ***should***(?) be fixed in the newest release, but since there seems to be another issue with that, I'll get back to you on whether I can close this or not

**Comment by MaxNeedsSnacks** [comment]
https://www.curseforge.com/minecraft/mc-mods/ftb-quests/files/3213290
