### ISSUE TITLE
[1.16.4] Crash with items

### ISSUE THREAD

**Issue by andreadx95** [FTBTeam/FTB-Quests#545]
**Mod Version:**
ftb-quests-1605.2.0-build.29-forge
item-filters-1605.2.4-build.29

**Issue**
Adding item to the quest cause force exit from the world giving this error log:

```
Description: Unexpected error

java.lang.NoSuchMethodError: dev.latvian.mods.itemfilters.api.ItemFiltersAPI.getDisplayItemStacks(Lnet/minecraft/item/ItemStack;Ljava/util/List;)V
	at com.feed_the_beast.ftbquests.quest.task.ItemTask.getValidDisplayItems(ItemTask.java:136) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.task.ItemTask.getAltIcon(ItemTask.java:158) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.getIcon(QuestObjectBase.java:297) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.Quest.getAltIcon(Quest.java:509) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.getIcon(QuestObjectBase.java:297) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.gui.quests.ButtonQuest.<init>(ButtonQuest.java:51) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.gui.quests.PanelQuests.addWidgets(PanelQuests.java:149) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.Panel.refreshWidgets(Panel.java:71) ~[?:?] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.task.Task.editedFromGUI(Task.java:154) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.client.FTBQuestsNetClient.createObject(FTBQuestsNetClient.java:79) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.net.MessageCreateObjectResponse.handle(MessageCreateObjectResponse.java:55) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.net.MessageBase.lambda$handle$0(MessageBase.java:17) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.net.MessageBase$$Lambda$20477/5376510.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?] {re:classloading}
	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$1.queue(NetworkManagerImpl.java:114) ~[?:?] {re:classloading}
	at com.feed_the_beast.ftbquests.net.MessageBase.handle(MessageBase.java:17) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.net.FTBQuestsNetHandler$$Lambda$7520/898122683.accept(Unknown Source) ~[?:?] {}
	at me.shedaniel.architectury.networking.NetworkChannel.lambda$register$1(NetworkChannel.java:79) ~[?:?] {re:classloading}
	at me.shedaniel.architectury.networking.NetworkChannel$$Lambda$5469/1841850886.receive(Unknown Source) ~[?:?] {}
	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$7(NetworkManagerImpl.java:106) ~[?:?] {re:classloading}
	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$$Lambda$5491/605724501.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2916/877706515.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$19797/1383341313.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[?:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_cleanup,xf:fml:xaerominimap:xaero_clientplaynethandler_cleanup,xf:fml:xaeroworldmap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlechunkdata,xf:fml:xaerominimap:xaero_clientplaynethandler_handlechunkdata,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaeroworldmap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:creativecore:clientnetwork,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandlerclass,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil$$Lambda$20073/1314761508.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.36.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$488/1131963943.call(Unknown Source) [forge-1.16.4-35.1.36.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.feed_the_beast.ftbquests.quest.task.ItemTask.getValidDisplayItems(ItemTask.java:136) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.task.ItemTask.getAltIcon(ItemTask.java:158) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.getIcon(QuestObjectBase.java:297) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.Quest.getAltIcon(Quest.java:509) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.getIcon(QuestObjectBase.java:297) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.gui.quests.ButtonQuest.<init>(ButtonQuest.java:51) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.gui.quests.PanelQuests.addWidgets(PanelQuests.java:149) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.Panel.refreshWidgets(Panel.java:71) ~[?:?] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.task.Task.editedFromGUI(Task.java:154) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.client.FTBQuestsNetClient.createObject(FTBQuestsNetClient.java:79) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.net.MessageCreateObjectResponse.handle(MessageCreateObjectResponse.java:55) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.net.MessageBase.lambda$handle$0(MessageBase.java:17) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.net.MessageBase$$Lambda$20477/5376510.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?] {re:classloading}
	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$1.queue(NetworkManagerImpl.java:114) ~[?:?] {re:classloading}
	at com.feed_the_beast.ftbquests.net.MessageBase.handle(MessageBase.java:17) ~[?:1605.2.0-build.29] {re:classloading}
	at com.feed_the_beast.ftbquests.net.FTBQuestsNetHandler$$Lambda$7520/898122683.accept(Unknown Source) ~[?:?] {}
	at me.shedaniel.architectury.networking.NetworkChannel.lambda$register$1(NetworkChannel.java:79) ~[?:?] {re:classloading}
	at me.shedaniel.architectury.networking.NetworkChannel$$Lambda$5469/1841850886.receive(Unknown Source) ~[?:?] {}
	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$7(NetworkManagerImpl.java:106) ~[?:?] {re:classloading}
	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$$Lambda$5491/605724501.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2916/877706515.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$19797/1383341313.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[?:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_cleanup,xf:fml:xaerominimap:xaero_clientplaynethandler_cleanup,xf:fml:xaeroworldmap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlechunkdata,xf:fml:xaerominimap:xaero_clientplaynethandler_handlechunkdata,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaeroworldmap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:creativecore:clientnetwork,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandlerclass,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil$$Lambda$20073/1314761508.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Andreadx_95'/53, l='ClientLevel', x=1405.76, y=67.56, z=2221.79]]
	Chunk stats: Client Chunk Cache: 4761, 3969
	Level dimension: minecraft:overworld
	Level spawn location: World: (-240,73,-224), Chunk: (at 0,4,0 in -15,-14; contains blocks -240,0,-224 to -225,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 710157 game time, 24264 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:betterweather.mixins.json:client.MixinClientWorld,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.36.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$488/1131963943.call(Unknown Source) [forge-1.16.4-35.1.36.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

```

**Comment by MaxNeedsSnacks** [comment]
Can you provide a full latest.log or debug.log uploaded to a site like pastebin? This doesn’t seem right

**Comment by andreadx95** [comment]
No problem , there is a limit on pastebin up to 512KB
so i attached as GDrive FIle : https://drive.google.com/file/d/1XHCiHo_nc3Ua3ruBWjyEj7XMhCjCn5rc/view?usp=sharing

**Comment by MaxNeedsSnacks** [comment]
> item-filters-1605.2.4-build.29
You're not on Item Filters build 29, see the crash report:

`		item-filters-1605.2.4.28-forge.jar                |Item Filters                  |itemfilters                   |1605.2.4.28         |DONE      |NOSIGNATURE`

Please update to build 29, that should've fixed that issue

**Comment by andreadx95** [comment]
sorry i've sent the old log , after i've installed Item Filters , and the same error happening , i will try again and send log from a new world if this should happen again
