### ISSUE TITLE
[1.12.2] JEI Mod added a tree entry after memory optimization!

### ISSUE THREAD

**Issue by juraj-hrivnak** [FTBTeam/FTB-Quests#574]
- This error occurs on entering the world

- FTB quest version
1202.9.0.15

### latest log: https://paste.ee/p/4mTsF
> modlist is included in the log

```less
java.lang.UnsupportedOperationException: null
	at it.unimi.dsi.fastutil.chars.AbstractChar2ObjectFunction.put(AbstractChar2ObjectFunction.java:119) ~[fastutil-7.1.0.jar:?]
	at mezz.jei.suffixtree.Node.addEdge(Node.java:124) ~[Node.class:?]
	at mezz.jei.suffixtree.GeneralizedSuffixTree.testAndSplit(GeneralizedSuffixTree.java:225) ~[GeneralizedSuffixTree.class:?]
	at mezz.jei.suffixtree.GeneralizedSuffixTree.update(GeneralizedSuffixTree.java:364) ~[GeneralizedSuffixTree.class:?]
	at mezz.jei.suffixtree.GeneralizedSuffixTree.put(GeneralizedSuffixTree.java:166) ~[GeneralizedSuffixTree.class:?]
	at mezz.jei.ingredients.IngredientFilter.addIngredient(IngredientFilter.java:126) ~[IngredientFilter.class:?]
	at mezz.jei.ingredients.IngredientRegistry.addIngredientsAtRuntime(IngredientRegistry.java:277) ~[IngredientRegistry.class:?]
	at mezz.jei.ingredients.IngredientRegistry.addIngredientsAtRuntime(IngredientRegistry.java:222) ~[IngredientRegistry.class:?]
	at com.feed_the_beast.ftbquests.integration.jei.LootCrateRegistry.refresh(LootCrateRegistry.java:55) ~[LootCrateRegistry.class:?]
	at com.feed_the_beast.ftbquests.integration.jei.FTBQuestsJEIHelper.refreshLootcrates(FTBQuestsJEIHelper.java:39) ~[FTBQuestsJEIHelper.class:?]
	at com.feed_the_beast.ftbquests.integration.jei.FTBQuestsJEIHelper.refresh(FTBQuestsJEIHelper.java:27) ~[FTBQuestsJEIHelper.class:?]
	at com.feed_the_beast.ftbquests.client.ClientQuestFile.load(ClientQuestFile.java:122) ~[ClientQuestFile.class:?]
	at com.feed_the_beast.ftbquests.net.MessageSyncQuests.onMessage(MessageSyncQuests.java:172) ~[MessageSyncQuests.class:?]
	at com.feed_the_beast.ftblib.client.FTBLibClient.handleClientMessage(FTBLibClient.java:69) ~[FTBLibClient.class:?]
	at com.feed_the_beast.ftblib.lib.net.MessageToClientHandler.lambda$onMessage$0(MessageToClientHandler.java:19) ~[MessageToClientHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_291]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_291]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by MaxNeedsSnacks** [comment]
In addition to 1.12 being unsupported anyways, your paste seems to have been removed from the platform since, so I can't really help with this unfortunately :/
