### ISSUE TITLE
Crash upon setting achievement quest using wrong text, locking all worlds.

### ISSUE THREAD

**Issue by TacocaTYT** [FTBTeam/FTB-Quests#590]
[21:17:46] [Server thread/FATAL]: Preparing crash report with UUID 9143f827-a655-4d3d-96b6-ca46b8c8f00a
[21:17:46] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$10960/936561183.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:A Seedy Place
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?]
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38) ~[?:?]
	at com.feed_the_beast.ftbquests.quest.task.AdvancementTask$Data.canSubmit(AdvancementTask.java:138) ~[?:1605.2.1-build.39]
	at com.feed_the_beast.ftbquests.quest.task.BooleanTaskData.submitTask(BooleanTaskData.java:21) ~[?:1605.2.1-build.39]
	at com.feed_the_beast.ftbquests.quest.task.TaskData.submitTask(TaskData.java:120) ~[?:1605.2.1-build.39]
	at com.feed_the_beast.ftbquests.FTBQuestsEventHandler.playerTick(FTBQuestsEventHandler.java:147) ~[?:1605.2.1-build.39]
	at com.feed_the_beast.ftbquests.FTBQuestsEventHandler$$Lambda$5955/66023111.tick(Unknown Source) ~[?:?]
	at me.shedaniel.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:138) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler_329_EventHandlerImplCommon_event_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2542/709877692.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPostTick(BasicEventHooks.java:90) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:266) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	... 7 more
[21:17:47] [Render thread/INFO]: Starting JEI...
[21:17:53] [Render thread/INFO]: Added recipe manager plugin: class com.valkyrieofnight.vlib.integration.jei.VLJEIRecipeManager
[21:17:53] [Render thread/INFO]: Building ingredient list...
[21:17:53] [Render thread/INFO]: Building ingredient list took 4.042 ms
[21:17:53] [Render thread/INFO]: Building ingredient filter...
[21:17:53] [Render thread/INFO]: Building ingredient filter took 537.5 ms
[21:17:53] [Render thread/INFO]: Building bookmarks...
[21:17:53] [Render thread/INFO]: Building bookmarks took 972.5 ?s
[21:17:53] [Render thread/INFO]: Building recipe registry...
[21:17:53] [Render thread/INFO]: Building recipe registry took 189.6 ms
[21:17:53] [Render thread/INFO]: Building runtime...
[21:17:53] [Render thread/INFO]: Building runtime took 38.38 ms
[21:17:53] [Render thread/INFO]: Starting JEI took 6.208 s

**Comment by pm065** [comment]
You can probably temporarily fix this by going to config/ftbquests and fixing it manually

**Comment by TacocaTYT** [comment]
yes that wokred but still this should be looked into

**Comment by MaxNeedsSnacks** [comment]
This should have been solved in one of the new FTB Quests builds (any builds starting from the one from four days ago) as the Advancement Task now works differently (using a map of existing advancements rather than letting you enter a custom string)

If this still manages to pop up (for example if the new system doesn't show up the old one is used as a fallback) somehow please reopen this so I can fix that as well!
